### PR TITLE
For ase>=3.18 & pickle wo OUTCAR

### PR DESCRIPTION
**Pull request by JisuJung928**
1. setup.py
 *  check user's python version and install proper version of ase because ase >= 3.18 does not support python < 3.5
2. compress outcar
 * ase >= 3.18 cannot conventional 'compressed outcar' without 'Iteration'
3. bytes string decode
 * for clear readability in log file

### CODE REVIEW

**Comment by JisuJung928** [comment]
check backward compatibility one more

**Comment by Nanco-L** [comment]
For structure energy, get_potential_energy(force_consistent=True) (for ase 3.18 or higher) may be correct. Please check it..

**Comment by JisuJung928** [comment]
if ase>3.18.0
 use get_potential_energy(force_consistent=True)
else 
 use get_total_energy()

**Comment by Nanco-L** [comment]
Change confirmed!

**Pull request merged**
